### ISSUE TITLE
base_url no longer requires an API version to be specified

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/VAST#2]
CanvasAPI only requires the protocol and domain name (e.g., `https://webcourses.ucf.edu`), so `README.txt` and `vast_config.template.py` should be updated to reflect that.

**Comment by bagofarms** [comment]
Updated the title because this error may only appear in Python3 or above.

**Comment by Thetwam** [comment]
I don't believe this is specific to Python 3.

As of CanvasAPI v0.8.0 (released in January), API version is no longer required (and in fact should be omitted), regardless of Python version.

**Comment by bagofarms** [comment]
Removed Python3 reference.  Pull request is up for someone to review.
