### ISSUE TITLE
Python3:  TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bagofarms** [ucfopen/VAST#3]
The traceback points to [vast.py line 405](https://github.com/ucfopen/VAST/blob/master/vast.py#L405).  It looks like this is because the file is being opened in binary mode, and Python3 is strict about using binary data for files that are opened as binary.

**Comment by Thetwam** [comment]
The README lists this project as only using Python 2.7.

Updating to 3 is definitely something we should do, but at the moment there is no official support for 3.

**Comment by bagofarms** [comment]
The "fix" would be removing the `b` flag from the file open operation, but as you mentioned in-person, that would probably break on any unicode content that would need to be written to the file.  I'm closing this issue since a migration to Python3 would be a larger undertaking than this one issue.
